version: "3.8"

services:
  conexa-challenge:
    container_name: conexa-backend
    image: conexa-challenge:latest
    
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
